### ISSUE TITLE
peer to peer code review

### ISSUE THREAD

**Issue by saied2035** [Bavon101/my_portfolio#8]
### **reviewing PR https://github.com/Bavon101/my_portfolio/pull/7**

you did a great work in this project just one thing to say. can you make your commits more descriptive ? to show exactly what you did.

**Comment by Bavon101** [comment]
> ### **reviewing PR #7**
> you did great work on this project just one thing to say. can you make your commits more descriptive? to show exactly what you did.
@saied2035 Thank you for noticing the issues, I'll work to improve on that.

**Comment by harlexkhal** [comment]
- Nice portfiolio. never seen a better one. you could make your CSS codes look a little bit cleaner by creating one `@media query` block for every of your desktop class identifiers instead of creating a different `@media query` block for each one. that would make your CSS codes look more organised and well sectioned.

**Comment by Bavon101** [comment]
> * Nice portfolio. never seen a better one. you could make your CSS codes look a little bit cleaner by creating one `@media query` block for every one of your desktop-class identifiers instead of creating a different `@media query` block for each one. that would make your CSS codes look more organized and well sectioned.

@harlexkhal  Thank you for your recommendations I'll work to improve this.,
